### ISSUE TITLE
Transferring issue from incorrect repo

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/python-p3-quiz-class-attributes-and-class-methods#1]
### Canvas Link

https://learning.flatironschool.com/courses/6559/quizzes/47505

### Concern

Question 6
1 / 1 pts
Consider the following code:

class Book:

genres = []

def init(self, title, author = "", page_count = 0):
self.title = title
self.author = author
self.page_count = page_count

def genre(self, genre):
return GENRE

Every time a genre is added to a Book object, we want to store that genre in the class variable named genres. The code above doesn't currently do this. Select the code snippet that does.

class Book:
genres = []

def init(self, title, author = "", page_count = 0):
self.title = title
self.author = author
self.page_count = page_count

def genre(cls, genre):
return cls.genres.append(genre)

Wow! Nailed it!! By calling cls.genres.append adding the genre to genres, we achieve exactly what we want.

class Book:
genres = []

def init(self, title, author = "", page_count = 0):
self.title = title
self.author = author
self.page_count = page_count

def genre(cls, genre):
return genres.append(genre)
3. I don't know.

The only problem is that you need https://github.com/classmethod just above the method; otherwise cls is just a normal parameter.

### Additional Context

This issue was originally posted by @ckelly38 here: https://github.com/learn-co-curriculum/phase-3-quiz-class-variables-and-methods/issues/3

### Suggested Changes

The only problem is that you need https://github.com/classmethod just above the method; otherwise cls is just a normal parameter. So add https://github.com/classmethod above each of the definitions for the genre method.

**Comment by linda-seiter** [comment]
fixed PR #2
